In [23]:
from bs4 import BeautifulSoup

In [24]:
import requests
import re
import pandas as pd

In [3]:
#url = "http://catalog.ncsu.edu/course-descriptions/csc/"
#url1 = "https://catalog.uncc.edu/content.php?catoid=19&navoid=1167"
#url2 = "https://catalog.unc.edu/courses/"
#url3 = "https://catalogs.gsu.edu/"
#def extraction():
    #result = requests.get(url)
   # doc = BeautifulSoup(result.text, "html.parser")
   # description = doc.find_all("div", attrs={"class","courseblock"})
   # data = []
   # for i in range(len(description)):
        #q = (description[i].find("div").text)
   #     data.append(description[i].find("div").text.replace('\xa0',' '))
   #     data.append(description[i].find("p").text.replace('\xa0',' '))
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
   # return data
#desc = doc.find_all("ul", attrs={"class","nav levelone"})
#parent = desc[0].parent
#lists =[]
#lists = parent.find_all("li")
#print(description)

#print(desc)
#courses = extraction()
#courses

In [4]:
base_url = "http://catalog.ncsu.edu/course-descriptions/"
result1 = requests.get(base_url)
doc1 = BeautifulSoup(result1.text, "html.parser")
description1 = doc1.find_all("ul", attrs={"class","nav levelone"})
data1,data2 = [],[]

for i in range(len(description1)):
    q = description1[i].find_all("li")
        #data1.append(description1[i].find_all("li"))
for j in range(len(q)):
    data1.append(q[j].a.text.replace('\u200b',''))
print(data1)
#print(len(data1))
for k in data1:
    data2.append(re.search(r"\((.*?)\)", k).group(1))
data2
#len(data2)

['Academy of Data Science (DSC)', 'Accounting (ACC)', 'Adult & Higher Education (EAC)', 'Advanced Analytics (AA)', 'Aerospace Studies (AS)', 'Africana Studies (AFS)', 'Agricultural and Extension Education (AEE)', 'Agricultural Economics (ARE)', 'Agricultural Institute (AGI)', 'Agriculture and Life Sciences (ALS)', 'Animal Science (ANS)', 'Anthropology (ANT)', 'Applied Ecology (AEC)', 'Architecture (ARC)', 'Art and Design (ADN)', 'Arts Studies (ARS)', 'Arts Village (AVS)', 'Biochemistry (BCH)', 'Biological and Agricultural Engineering (BAE)', 'Biological Sciences (BIO)', 'Biomanufacturing Training Education Center (BEC)', 'Biomathematics (BMA)', 'Biomedical Engineering (BME)', 'Bioprocessing (BBS)', 'Biotechnology (BIT)', 'Business Administration (MBA)', 'Business Management (BUS)', 'Chemical Engineering (CHE)', 'Chemistry (CH)', 'Civil Engineering (CE)', 'College of Natural Resources (CNR)', 'College of Sciences (COS)', 'Communication (COM)', 'Communication Rhetoric & Digital Media (CRD)', 'Comparative Biological Science (CBS)', 'Comparative Literature (CL)', 'Computer Science (CSC)', 'Cooperative Education (COP)', 'Counselor Education (ECD)', 'Crop Science (CS)', 'Curriculum and Instruction (ECI)', 'Dance (DAN)', 'Design (D)', 'Design courses for Graduate Students (DDN)', 'Design Studies (DS)', 'Ecology (ECO)', 'Economics (EC)', 'Educ Leadership & Program Eval (ELP)', 'Education (ED)', 'Educational Psychology (EDP)', "EGR-Engineering Master's (EGR)", 'Electrical and Computer Engineering (ECE)', 'Elementary Education (ELM)', 'Engineering (E)', 'English (ENG)', 'Entomology (ENT)', 'Entrepreneurship in Music and the Arts (EMA)', 'Entrepreneurship Initiative (EI)', 'Environmental Assessment (EA)', 'Environmental Science (ES)', 'Environmental Technology (ET)', 'Fashion and Textile Design (FTD)', 'Fashion and Textile Management (FTM)', 'Feed Mill (FM)', 'Fiber and Polymer Science (FPS)', 'Financial Mathematics (FIM)', 'Fisheries & Wildlife Sciences (FW)', 'Food Science (FS)', 'Food Science (FSA)', 'Foreign Language - Chinese (FLC)', 'Foreign Language - English (FLE)', 'Foreign Language - French (FLF)', 'Foreign Language - German (FLG)', 'Foreign Language - Greek (GRK)', 'Foreign Language - Hindi (FLN)', 'Foreign Language - Italian (FLI)', 'Foreign Language - Japanese (FLJ)', 'Foreign Language - Latin (LAT)', 'Foreign Language - Persian (PER)', 'Foreign Language - Portuguese (FLP)', 'Foreign Language - Russian (FLR)', 'Foreign Language - Spanish (FLS)', 'Foreign Language-Classical Studies (CLA)', 'Foreign Languages (FL)', 'Foreign Languages and Literatures - Arabic (FLA)', 'Forestry (FOR)', 'Genetic Engineering and Society (GES)', 'Genetics (GN)', 'Geographic Information Systems (GIS)', 'Geography (GEO)', 'Global Knowledge (GK)', 'Global Public Health (GPH)', 'Graduate Economics (ECG)', 'Graphic Communications (GC)', 'Graphic Design (GD)', 'Health and Exercise Studies Minor (HESM)', 'Health Exercise Studies Dance (HESD)', 'Health Exercise Studies Fitness (HESF)', 'Health Exercise Studies Outdoor (HESO)', 'Health Exercise Studies Racquet (HESR)', 'Health Exercise Studies Specialty (HESS)', 'Health Exercise Studies Team (HEST)', 'HESA - Health Exercise Aquatics (HESA)', 'History (HI)', 'History of Art (HA)', 'Honors (HON)', 'Horticulture Science (HS)', 'Humanites and Social Sciences (HSS)', 'Humanities (HUM)', 'Humanities and Global Knowledge (HUMG)', 'Humanities and U.S. Diversity (HUMU)', 'Immunology (IMM)', 'Industrial and Systems Engineering (ISE)', 'Industrial Design (ID)', 'Integrated Manufacturing Systems (IMS)', 'Interdisciplinary Perspectives (IPGE)', 'Interdisciplinary Perspectives and Global Knowledg (IPGK)', 'Interdisciplinary Perspectives and U.S. Diversity (IPUS)', 'Interdisciplinary Studies (IDS)', 'International Studies (IS)', 'International Studies (MIS)', 'Landscape Architecture (LAR)', 'Leadership in the Public Sector (LPS)', 'Liberal Studies (MLS)', 'Life Sciences First Year (LSC)', 'Logic (LOG)', 'Management  Innovation  Entrepreneurship (MIE)', 'Management (M)', 'Marine, Earth, and Atmospheric Sciences (MEA)', 'Materials Science and Engineering (MSE)', 'Math & Science Education (EMS)', 'Math in Agriculture and Related Sciences (MAA)', 'Mathematical Sciences (MSGE)', 'Mathematics (MA)', 'Mechanical & Aerospace Engr (MAE)', 'Mechanical Engineering Systems (MES)', 'Medical Textiles (MT)', 'Microbiology (MB)', 'Military Science (MS)', 'Multidisciplinary Studies (MDS)', 'Music (MUS)', 'Natural Resources (NR)', 'Natural Sciences (NSGE)', 'Natural Sciences and Global Knowledge (NSGK)', 'Naval Science (NS)', 'NC Global Training Initiative (GTI)', 'Nonprofit Studies (NPS)', 'Nonwovens (NW)', 'Nuclear Engineering (NE)', 'Nutrition (NTR)', 'Occupational Education (EOE)', 'Operations Research (OR)', 'Paper Science Engineering (PSE)', 'Park Scholars (PRK)', 'Parks, Recreation, and Tourism Management (PRT)', 'Philosophy (PHI)', 'Physics (PY)', 'Physiology (PHY)', 'Plant Biology (PB)', 'Plant Pathology (PP)', 'Political Science (PS)', 'Polymer and Color Chemistry (PCC)', 'Poultry Science (PO)', 'Professional Writing (WRT)', 'Psychology (PSY)', 'Public Administration (PA)', 'Religious Studies (REL)', 'Science, Technology and Society (STS)', 'Social Sciences (SSGE)', 'Social Sciences and Global Knowledge (SSGK)', 'Social Sciences and U.S. Diversity (SSUS)', 'Social Work (SW)', 'Sociology (SOC)', 'Soil Science (SSC)', 'Statistics (ST)', 'Sustanaible Materials and Technology (SMT)', 'Technology Education (TED)', 'Technology Engineering and Design Education (TDE)', 'Textile and Apparel Management (TAM)', 'Textile Chemistry (TC)', 'Textile Engineering (TE)', 'Textile Materials Science (TMS)', 'Textile Technology (TT)', 'Textile Technology Management (TTM)', 'Textiles (T)', 'Theatre (THE)', 'Toxicology (TOX)', 'U.S. Diversity (USD)', 'University Scholars Program (USP)', 'University Studies Course (USC)', 'Veterinary Medicine-Companion Animal & Sp Species (VMC)', 'Veterinary Science - VMB (VMB)', 'Veterinary Science - VMP (VMP)', 'Visual and Performing Arts (VPGE)', 'Visual and Performing Arts and Glob Know (VPGK)', 'Visual and Performing Arts and U.S. Div (VPUS)', "Women's, Gender and Sexuality Studies (WGS)", 'Wood and Paper Science (WPS)', 'Zoology (ZO)']

['DSC',
 'ACC',
 'EAC',
 'AA',
 'AS',
 'AFS',
 'AEE',
 'ARE',
 'AGI',
 'ALS',
 'ANS',
 'ANT',
 'AEC',
 'ARC',
 'ADN',
 'ARS',
 'AVS',
 'BCH',
 'BAE',
 'BIO',
 'BEC',
 'BMA',
 'BME',
 'BBS',
 'BIT',
 'MBA',
 'BUS',
 'CHE',
 'CH',
 'CE',
 'CNR',
 'COS',
 'COM',
 'CRD',
 'CBS',
 'CL',
 'CSC',
 'COP',
 'ECD',
 'CS',
 'ECI',
 'DAN',
 'D',
 'DDN',
 'DS',
 'ECO',
 'EC',
 'ELP',
 'ED',
 'EDP',
 'EGR',
 'ECE',
 'ELM',
 'E',
 'ENG',
 'ENT',
 'EMA',
 'EI',
 'EA',
 'ES',
 'ET',
 'FTD',
 'FTM',
 'FM',
 'FPS',
 'FIM',
 'FW',
 'FS',
 'FSA',
 'FLC',
 'FLE',
 'FLF',
 'FLG',
 'GRK',
 'FLN',
 'FLI',
 'FLJ',
 'LAT',
 'PER',
 'FLP',
 'FLR',
 'FLS',
 'CLA',
 'FL',
 'FLA',
 'FOR',
 'GES',
 'GN',
 'GIS',
 'GEO',
 'GK',
 'GPH',
 'ECG',
 'GC',
 'GD',
 'HESM',
 'HESD',
 'HESF',
 'HESO',
 'HESR',
 'HESS',
 'HEST',
 'HESA',
 'HI',
 'HA',
 'HON',
 'HS',
 'HSS',
 'HUM',
 'HUMG',
 'HUMU',
 'IMM',
 'ISE',
 'ID',
 'IMS',
 'IPGE',
 'IPGK',
 'IPUS',
 'IDS',
 'IS',
 'MIS',
 'LAR',
 'LPS',
 'MLS',
 'LSC',
 'LOG',
 'MIE',
 'M',
 'MEA',
 'MSE',
 'EMS',
 'MAA',
 'MSGE',
 'MA',
 'MAE',
 'MES',
 'MT',
 'MB',
 'MS',
 'MDS',
 'MUS',
 'NR',
 'NSGE',
 'NSGK',
 'NS',
 'GTI',
 'NPS',
 'NW',
 'NE',
 'NTR',
 'EOE',
 'OR',
 'PSE',
 'PRK',
 'PRT',
 'PHI',
 'PY',
 'PHY',
 'PB',
 'PP',
 'PS',
 'PCC',
 'PO',
 'WRT',
 'PSY',
 'PA',
 'REL',
 'STS',
 'SSGE',
 'SSGK',
 'SSUS',
 'SW',
 'SOC',
 'SSC',
 'ST',
 'SMT',
 'TED',
 'TDE',
 'TAM',
 'TC',
 'TE',
 'TMS',
 'TT',
 'TTM',
 'T',
 'THE',
 'TOX',
 'USD',
 'USP',
 'USC',
 'VMC',
 'VMB',
 'VMP',
 'VPGE',
 'VPGK',
 'VPUS',
 'WGS',
 'WPS',
 'ZO']

In [5]:

    #def extraction():
      #  data =[]
       # data_1 = []
       # for i1 in data2:
          #  result = requests.get(base_url+ i1.lower())
         #   print(result)
        #    doc = BeautifulSoup(result.text, "html.parser")
        #    description = doc.find_all("div", attrs={"class","courseblock"})
            
        #    for i in range(len(description)):
        #q = (description[i].find("div").text)
             #   data.append(description[i].find("div").text)
                
              #  if (description[i].find("p")):
               #     data_1.append(description[i].find("p").text)
              #  else:
              #      data_1.append("No description for this course")
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
       # return data,data_1
    
#courses = extraction()
#l = range(1, len(courses)+1)
#courses_df = pd.DataFrame({'courses':courses[0], 'description':courses[1]})
#courses_df.to_csv('courses.csv', sep = '\xa0')

In [9]:
    def extraction():
        data =[]
        data_1 = []
        data_2 =[]
        data_3 =[]
        
        for i1 in data2:
            result = requests.get(base_url+ i1.lower())
            print(result)
            doc = BeautifulSoup(result.text, "html.parser")
            description = doc.find_all("div", attrs={"class","courseblock"})
            
            for i in range(len(description)):
        #q = (description[i].find("div").text)
                data.append(description[i].find("strong").text)
                h= ((description[i].find_all("strong")))
                for h1 in h[1]:
                    data_1.append(h1.text)
                
                if (description[i].find("p")):
                    data_2.append(description[i].find("p").text)
                else:
                    data_2.append("No description for this course")
                data_3.append(i1)
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
        return data,data_1,data_2,data_3
    
courses = extraction()

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [33]:
courses_df = pd.DataFrame({'CourseNumber':courses[0], 'CourseTitle':courses[1], 'Description':courses[2], 'CourseDepartment':courses[3]})
courses_df.to_csv('../data/courses.csv', sep = '\xa0', index = None)

In [10]:
#url = "http://catalog.ncsu.edu/course-descriptions/csc/"
#url1 = "https://catalog.uncc.edu/content.php?catoid=19&navoid=1167"
#url2 = "https://catalog.unc.edu/courses/"
#url3 = "https://catalogs.gsu.edu/"
#def extraction():
 #   result = requests.get(url)
  #  doc = BeautifulSoup(result.text, "html.parser")
  #  description = doc.find_all("div", attrs={"class","courseblock"})
  #  data = []
  #  for i in range(len(description)):
        #q = (description[i].find("div").text)
        
  #      h= ((description[i].find_all("strong")))
   #     for i in h[1]:
   #         print(i.text)
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
   # return data
#desc = doc.find_all("ul", attrs={"class","nav levelone"})
#parent = desc[0].parent
#lists =[]
#lists = parent.find_all("li")
#print(description)

#print(desc)
#courses = extraction()
#courses

In [34]:
type(courses)

tuple

In [35]:
courses_df

,CourseNumber,CourseTitle,Description,CourseDepartment
0,DSC 495,Special Topics in Data Science,Offered as needed to present material not norm...,DSC
1,ACC 200,Introduction to Managerial Accounting,Analysis of accounting data that are useful i...,ACC
2,ACC 210,Concepts of Financial Reporting,"Financial reporting concepts, the accounting i...",ACC
3,ACC 220,Introduction to Managerial Accounting,The course is designed to provide students wit...,ACC
4,ACC 230,Individual Income Taxation,The course focuses on the fundamental concepts...,ACC
...,...,...,...,...
7256,ZO 553/FW 553,Principles Of Wildlife Science,The principles of wildlife management and thei...,ZO
7257,ZO 582/ENT 582,Medical and Veterinary Entomology,"The morphology, taxonomy, biology and control ...",ZO
7258,ZO 790,Special Topics,No description for this course,ZO
7259,ZO 791,Topics In Animal Behavior,Intensive examination of selected aspects of a...,ZO
7260,ZO 829,Special Topics,A directed individual investigation of a parti...,ZO

In [36]:
#len(data1)
len(courses_df)

7261

In [37]:
x = (courses_df.CourseDepartment.value_counts(sort=False))
xi2 = list(x)

In [12]:
 #def extraction():
  #      data =[]
  #      data_1 = []
  #      data_2 =[]
  #      data_3 =[]
        
  #      for i1 in data2[:2]:
  #          result = requests.get(base_url+ i1.lower())
  #          print(result)
   #         doc = BeautifulSoup(result.text, "html.parser")
   #         description = doc.find_all("div", attrs={"class","courseblock"})
            
   #         for i in range(len(description)):
        #q = (description[i].find("div").text)
   #             data.append(description[i].find("strong").text)
   #             h= ((description[i].find_all("strong")))
   #             for h1 in h[1]:
   #                 data_1.append(h1.text)
                
   #             if (description[i].find("p")):
   #                 data_2.append(description[i].find("p").text)
   #             else:
   #                 data_2.append("No description for this course")
    #            for i2 in data1[:i1]:
    #                data_3.append(i2)
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
     #   return data,data_1,data_2,data_3
    
#courses = extraction()
#courses_df = pd.DataFrame({'CourseNumber':courses[0], 'CourseTitle':courses[1], 'Description':courses[2], 'CourseDepartment':courses[3]})
#courses_df.to_csv('courses_test.csv', sep = '\xa0')

In [20]:
 def extraction():
        data =[]
        data_1 = []
        data_2 =[]
        data_3 =[]
        
        for i1 in data2[:3]:
            result = requests.get(base_url+ i1.lower())
            print(result)
            doc = BeautifulSoup(result.content, "html.parser")
            print(type(doc))
            description = doc.find_all("div", attrs={"class","courseblock"})
            print(type(description))
            
            for i in range(len(description)):
        #q = (description[i].find("div").text)
                data.append(description[i].find("strong").text)
                h= ((description[i].find_all("strong")))
                #for h0 in h[0]:
                    #data.append(h0.text)
                for h1 in h[1]:
                    data_1.append(h1.text)
                if (description[i].find("p")):
                        data_2.append(description[i].find("p").text)
                else:
                        data_2.append("No description for this course")

                if((description[i].find("em"))):
                    data_2.append(description[i].find("em").text)
                else:
                    data_2.append("No information")
                
                #for d1 in d:
                #if(d):
                    #data_2.append(d.text)
                #else:
                    #data_2.append("No information")
                data_3.append(i1)
            #print(d)
        
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
    
             
        return data,data_1,data_2,data_3
    
courses = extraction()
print(type(courses))

courses_df = pd.DataFrame({'CourseNumber':courses[0], 'CourseTitle':courses[1], 'Description':courses[2], 'CourseDepartment':courses[3]})
courses_df.to_csv('courses_test.csv')

' def extraction():\n        data =[]\n        data_1 = []\n        data_2 =[]\n        data_3 =[]\n        \n        for i1 in data2[:3]:\n            result = requests.get(base_url+ i1.lower())\n            print(result)\n            doc = BeautifulSoup(result.content, "html.parser")\n            print(type(doc))\n            description = doc.find_all("div", attrs={"class","courseblock"})\n            print(type(description))\n            \n            for i in range(len(description)):\n        #q = (description[i].find("div").text)\n                data.append(description[i].find("strong").text)\n                h= ((description[i].find_all("strong")))\n                #for h0 in h[0]:\n                    #data.append(h0.text)\n                for h1 in h[1]:\n                    data_1.append(h1.text)\n                if (description[i].find("p")):\n                        data_2.append(description[i].find("p").text)\n                else:\n                        data_2.append("No description for this course")\n\n                if((description[i].find("em"))):\n                    data_2.append(description[i].find("em").text)\n                else:\n                    data_2.append("No information")\n                \n                #for d1 in d:\n                #if(d):\n                    #data_2.append(d.text)\n                #else:\n                    #data_2.append("No information")\n                data_3.append(i1)\n            #print(d)\n        \n    #for i in data:\n        #i = i.replace(\'\xa0\',\'\')\n    #print(data)\n    \n             \n        return data,data_1,data_2,data_3\n    \ncourses = extraction()\nprint(type(courses))\n\ncourses_df = pd.DataFrame({\'CourseNumber\':courses[0], \'CourseTitle\':courses[1], \'Description\':courses[2], \'CourseDepartment\':courses[3]})\ncourses_df.to_csv(\'courses_test.csv\', sep = \' \')'

In [38]:
dept = []
for y in data1:
        dept.append(re.sub("[\(\[].*?[\)\]]", "", y))
#print(len(dept))
dept.remove('Ecology ')
dept

ValueError: list.remove(x): x not in list

In [31]:

lenlist=[]
for i in range(len(dept)):
    xi = int(xi2[i])
    while(xi!=0):
        lenlist.append(dept[i])
        xi = xi-1
        
lenlist
p1 = pd.DataFrame(lenlist)

In [32]:
p1

                             0
0     Academy of Data Science
1                  Accounting
2                  Accounting
3                  Accounting
4                  Accounting
...                        ...
7256                  Zoology
7257                  Zoology
7258                  Zoology
7259                  Zoology
7260                  Zoology

[7261 rows x 1 columns]

In [38]:
courses_df1 = pd.DataFrame({'CourseNumber':courses[0], 'CourseTitle':courses[1], 'Description':courses[2],'CourseDepartment':courses[3]})
courses_df1.to_csv('courses_temp.csv')

ValueError: All arrays must be of the same length

In [7]:
base_url = "http://catalog.ncsu.edu/course-descriptions/" 
result1 = requests.get(base_url)
print(result1)
doc1 = BeautifulSoup(result1.text, "html.parser")
description1 = doc1.find_all("ul", attrs={"class","nav levelone"})
data1,data2 = [],[]

for i in range(len(description1)):
    q = description1[i].find_all("li")
        #data1.append(description1[i].find_all("li"))
for j in range(len(q)):
    data1.append(q[j].a.text.replace('\u200b',''))
#for j1 in range(len(data1)):
    #if data1[j] =='Ecology (ECO)'
data1.remove('Ecology (ECO)')
print(data1)
#print(len(data1))
for k in data1:
    data2.append(re.search(r"\((.*?)\)", k).group(1))
data2

<Response [200]>
['Academy of Data Science (DSC)', 'Accounting (ACC)', 'Adult & Higher Education (EAC)', 'Advanced Analytics (AA)', 'Aerospace Studies (AS)', 'Africana Studies (AFS)', 'Agricultural and Extension Education (AEE)', 'Agricultural Economics (ARE)', 'Agricultural Institute (AGI)', 'Agriculture and Life Sciences (ALS)', 'Animal Science (ANS)', 'Anthropology (ANT)', 'Applied Ecology (AEC)', 'Architecture (ARC)', 'Art and Design (ADN)', 'Arts Studies (ARS)', 'Arts Village (AVS)', 'Biochemistry (BCH)', 'Biological and Agricultural Engineering (BAE)', 'Biological Sciences (BIO)', 'Biomanufacturing Training Education Center (BEC)', 'Biomathematics (BMA)', 'Biomedical Engineering (BME)', 'Bioprocessing (BBS)', 'Biotechnology (BIT)', 'Business Administration (MBA)', 'Business Management (BUS)', 'Chemical Engineering (CHE)', 'Chemistry (CH)', 'Civil Engineering (CE)', 'College of Natural Resources (CNR)', 'College of Sciences (COS)', 'Communication (COM)', 'Communication Rhetoric & Digital Media (CRD)', 'Comparative Biological Science (CBS)', 'Comparative Literature (CL)', 'Computer Science (CSC)', 'Cooperative Education (COP)', 'Counselor Education (ECD)', 'Crop Science (CS)', 'Curriculum and Instruction (ECI)', 'Dance (DAN)', 'Design (D)', 'Design courses for Graduate Students (DDN)', 'Design Studies (DS)', 'Economics (EC)', 'Educ Leadership & Program Eval (ELP)', 'Education (ED)', 'Educational Psychology (EDP)', "EGR-Engineering Master's (EGR)", 'Electrical and Computer Engineering (ECE)', 'Elementary Education (ELM)', 'Engineering (E)', 'English (ENG)', 'Entomology (ENT)', 'Entrepreneurship in Music and the Arts (EMA)', 'Entrepreneurship Initiative (EI)', 'Environmental Assessment (EA)', 'Environmental Science (ES)', 'Environmental Technology (ET)', 'Fashion and Textile Design (FTD)', 'Fashion and Textile Management (FTM)', 'Feed Mill (FM)', 'Fiber and Polymer Science (FPS)', 'Financial Mathematics (FIM)', 'Fisheries & Wildlife Sciences (FW)', 'Food Science (FS)', 'Food Science (FSA)', 'Foreign Language - Chinese (FLC)', 'Foreign Language - English (FLE)', 'Foreign Language - French (FLF)', 'Foreign Language - German (FLG)', 'Foreign Language - Greek (GRK)', 'Foreign Language - Hindi (FLN)', 'Foreign Language - Italian (FLI)', 'Foreign Language - Japanese (FLJ)', 'Foreign Language - Latin (LAT)', 'Foreign Language - Persian (PER)', 'Foreign Language - Portuguese (FLP)', 'Foreign Language - Russian (FLR)', 'Foreign Language - Spanish (FLS)', 'Foreign Language-Classical Studies (CLA)', 'Foreign Languages (FL)', 'Foreign Languages and Literatures - Arabic (FLA)', 'Forestry (FOR)', 'Genetic Engineering and Society (GES)', 'Genetics (GN)', 'Geographic Information Systems (GIS)', 'Geography (GEO)', 'Global Knowledge (GK)', 'Global Public Health (GPH)', 'Graduate Economics (ECG)', 'Graphic Communications (GC)', 'Graphic Design (GD)', 'Health and Exercise Studies Minor (HESM)', 'Health Exercise Studies Dance (HESD)', 'Health Exercise Studies Fitness (HESF)', 'Health Exercise Studies Outdoor (HESO)', 'Health Exercise Studies Racquet (HESR)', 'Health Exercise Studies Specialty (HESS)', 'Health Exercise Studies Team (HEST)', 'HESA - Health Exercise Aquatics (HESA)', 'History (HI)', 'History of Art (HA)', 'Honors (HON)', 'Horticulture Science (HS)', 'Humanites and Social Sciences (HSS)', 'Humanities (HUM)', 'Humanities and Global Knowledge (HUMG)', 'Humanities and U.S. Diversity (HUMU)', 'Immunology (IMM)', 'Industrial and Systems Engineering (ISE)', 'Industrial Design (ID)', 'Integrated Manufacturing Systems (IMS)', 'Interdisciplinary Perspectives (IPGE)', 'Interdisciplinary Perspectives and Global Knowledg (IPGK)', 'Interdisciplinary Perspectives and U.S. Diversity (IPUS)', 'Interdisciplinary Studies (IDS)', 'International Studies (IS)', 'International Studies (MIS)', 'Landscape Architecture (LAR)', 'Leadership in the Public Sector (LPS)', 'Liberal Studies (MLS)', 'Life Sciences First Year (LSC)', 'Logic (LOG)', 'Management  Innovation  Entrepreneurship (MIE)', 'Management (M)', 'Marine, Earth, and Atmospheric Sciences (MEA)', 'Materials Science and Engineering (MSE)', 'Math & Science Education (EMS)', 'Math in Agriculture and Related Sciences (MAA)', 'Mathematical Sciences (MSGE)', 'Mathematics (MA)', 'Mechanical & Aerospace Engr (MAE)', 'Mechanical Engineering Systems (MES)', 'Medical Textiles (MT)', 'Microbiology (MB)', 'Military Science (MS)', 'Multidisciplinary Studies (MDS)', 'Music (MUS)', 'Natural Resources (NR)', 'Natural Sciences (NSGE)', 'Natural Sciences and Global Knowledge (NSGK)', 'Naval Science (NS)', 'NC Global Training Initiative (GTI)', 'Nonprofit Studies (NPS)', 'Nonwovens (NW)', 'Nuclear Engineering (NE)', 'Nutrition (NTR)', 'Occupational Education (EOE)', 'Operations Research (OR)', 'Paper Science Engineering (PSE)', 'Park Scholars (PRK)', 'Parks, Recreation, and Tourism Management (PRT)', 'Philosophy (PHI)', 'Physics (PY)', 'Physiology (PHY)', 'Plant Biology (PB)', 'Plant Pathology (PP)', 'Political Science (PS)', 'Polymer and Color Chemistry (PCC)', 'Poultry Science (PO)', 'Professional Writing (WRT)', 'Psychology (PSY)', 'Public Administration (PA)', 'Religious Studies (REL)', 'Science, Technology and Society (STS)', 'Social Sciences (SSGE)', 'Social Sciences and Global Knowledge (SSGK)', 'Social Sciences and U.S. Diversity (SSUS)', 'Social Work (SW)', 'Sociology (SOC)', 'Soil Science (SSC)', 'Statistics (ST)', 'Sustanaible Materials and Technology (SMT)', 'Technology Education (TED)', 'Technology Engineering and Design Education (TDE)', 'Textile and Apparel Management (TAM)', 'Textile Chemistry (TC)', 'Textile Engineering (TE)', 'Textile Materials Science (TMS)', 'Textile Technology (TT)', 'Textile Technology Management (TTM)', 'Textiles (T)', 'Theatre (THE)', 'Toxicology (TOX)', 'U.S. Diversity (USD)', 'University Scholars Program (USP)', 'University Studies Course (USC)', 'Veterinary Medicine-Companion Animal & Sp Species (VMC)', 'Veterinary Science - VMB (VMB)', 'Veterinary Science - VMP (VMP)', 'Visual and Performing Arts (VPGE)', 'Visual and Performing Arts and Glob Know (VPGK)', 'Visual and Performing Arts and U.S. Div (VPUS)', "Women's, Gender and Sexuality Studies (WGS)", 'Wood and Paper Science (WPS)', 'Zoology (ZO)']

['DSC',
 'ACC',
 'EAC',
 'AA',
 'AS',
 'AFS',
 'AEE',
 'ARE',
 'AGI',
 'ALS',
 'ANS',
 'ANT',
 'AEC',
 'ARC',
 'ADN',
 'ARS',
 'AVS',
 'BCH',
 'BAE',
 'BIO',
 'BEC',
 'BMA',
 'BME',
 'BBS',
 'BIT',
 'MBA',
 'BUS',
 'CHE',
 'CH',
 'CE',
 'CNR',
 'COS',
 'COM',
 'CRD',
 'CBS',
 'CL',
 'CSC',
 'COP',
 'ECD',
 'CS',
 'ECI',
 'DAN',
 'D',
 'DDN',
 'DS',
 'EC',
 'ELP',
 'ED',
 'EDP',
 'EGR',
 'ECE',
 'ELM',
 'E',
 'ENG',
 'ENT',
 'EMA',
 'EI',
 'EA',
 'ES',
 'ET',
 'FTD',
 'FTM',
 'FM',
 'FPS',
 'FIM',
 'FW',
 'FS',
 'FSA',
 'FLC',
 'FLE',
 'FLF',
 'FLG',
 'GRK',
 'FLN',
 'FLI',
 'FLJ',
 'LAT',
 'PER',
 'FLP',
 'FLR',
 'FLS',
 'CLA',
 'FL',
 'FLA',
 'FOR',
 'GES',
 'GN',
 'GIS',
 'GEO',
 'GK',
 'GPH',
 'ECG',
 'GC',
 'GD',
 'HESM',
 'HESD',
 'HESF',
 'HESO',
 'HESR',
 'HESS',
 'HEST',
 'HESA',
 'HI',
 'HA',
 'HON',
 'HS',
 'HSS',
 'HUM',
 'HUMG',
 'HUMU',
 'IMM',
 'ISE',
 'ID',
 'IMS',
 'IPGE',
 'IPGK',
 'IPUS',
 'IDS',
 'IS',
 'MIS',
 'LAR',
 'LPS',
 'MLS',
 'LSC',
 'LOG',
 'MIE',
 'M',
 'MEA',
 'MSE',
 'EMS',
 'MAA',
 'MSGE',
 'MA',
 'MAE',
 'MES',
 'MT',
 'MB',
 'MS',
 'MDS',
 'MUS',
 'NR',
 'NSGE',
 'NSGK',
 'NS',
 'GTI',
 'NPS',
 'NW',
 'NE',
 'NTR',
 'EOE',
 'OR',
 'PSE',
 'PRK',
 'PRT',
 'PHI',
 'PY',
 'PHY',
 'PB',
 'PP',
 'PS',
 'PCC',
 'PO',
 'WRT',
 'PSY',
 'PA',
 'REL',
 'STS',
 'SSGE',
 'SSGK',
 'SSUS',
 'SW',
 'SOC',
 'SSC',
 'ST',
 'SMT',
 'TED',
 'TDE',
 'TAM',
 'TC',
 'TE',
 'TMS',
 'TT',
 'TTM',
 'T',
 'THE',
 'TOX',
 'USD',
 'USP',
 'USC',
 'VMC',
 'VMB',
 'VMP',
 'VPGE',
 'VPGK',
 'VPUS',
 'WGS',
 'WPS',
 'ZO']

In [34]:
 def extraction1():
        data =[]
        data_1 = []
        data_2 =[]
        data_3 =[]
        
        for i1 in data2:
            result = requests.get(base_url+ i1.lower())
            print(result)
            doc = BeautifulSoup(result.text, "html.parser")
            description = doc.find_all("div", attrs={"class","courseblock"})
            
            for i in range(len(description)):
        #q = (description[i].find("div").text)
                data.append(description[i].find("strong").text.replace("\xa0"," "))
                h= ((description[i].find_all("strong")))
                for h1 in h[1]:
                    data_1.append(h1.text)
                
                if (description[i].find("p")):
                    data_2.append(description[i].find("p").text)
                else:
                    data_2.append("No description for this course")
                data_3.append(i1)
    #for i in data:
        #i = i.replace('\xa0','')
    #print(data)
        return data,data_1,data_2,data_3
    
courses1 = extraction1()

#courses_df_1 = pd.DataFrame({'CourseNumber':courses1[0], 'CourseTitle':courses1[1], 'Description':courses1[2], 'CourseDepartment':courses1[3]})
#courses_df_1.to_csv('courses_temp1.csv', sep = '\xa0')

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

In [35]:
courses_df_1 = pd.DataFrame({'CourseNumber':courses1[0], 'CourseTitle':courses1[1], 'Description':courses1[2], 'CourseDepartment':courses1[3]})
courses_df_1.to_csv('../data/courses_temp1.csv', index = None)

In [36]:
len(courses_df_1)

7261

In [37]:
dept1 = []
for y in data1:
        dept1.append(re.sub(" [\(\[].*?[\)\]]", "", y))
print(len(dept1))
dept1

198

['Academy of Data Science',
 'Accounting',
 'Adult & Higher Education',
 'Advanced Analytics',
 'Aerospace Studies',
 'Africana Studies',
 'Agricultural and Extension Education',
 'Agricultural Economics',
 'Agricultural Institute',
 'Agriculture and Life Sciences',
 'Animal Science',
 'Anthropology',
 'Applied Ecology',
 'Architecture',
 'Art and Design',
 'Arts Studies',
 'Arts Village',
 'Biochemistry',
 'Biological and Agricultural Engineering',
 'Biological Sciences',
 'Biomanufacturing Training Education Center',
 'Biomathematics',
 'Biomedical Engineering',
 'Bioprocessing',
 'Biotechnology',
 'Business Administration',
 'Business Management',
 'Chemical Engineering',
 'Chemistry',
 'Civil Engineering',
 'College of Natural Resources',
 'College of Sciences',
 'Communication',
 'Communication Rhetoric & Digital Media',
 'Comparative Biological Science',
 'Comparative Literature',
 'Computer Science',
 'Cooperative Education',
 'Counselor Education',
 'Crop Science',
 'Curriculum and Instruction',
 'Dance',
 'Design',
 'Design courses for Graduate Students',
 'Design Studies',
 'Economics',
 'Educ Leadership & Program Eval',
 'Education',
 'Educational Psychology',
 "EGR-Engineering Master's",
 'Electrical and Computer Engineering',
 'Elementary Education',
 'Engineering',
 'English',
 'Entomology',
 'Entrepreneurship in Music and the Arts',
 'Entrepreneurship Initiative',
 'Environmental Assessment',
 'Environmental Science',
 'Environmental Technology',
 'Fashion and Textile Design',
 'Fashion and Textile Management',
 'Feed Mill',
 'Fiber and Polymer Science',
 'Financial Mathematics',
 'Fisheries & Wildlife Sciences',
 'Food Science',
 'Food Science',
 'Foreign Language - Chinese',
 'Foreign Language - English',
 'Foreign Language - French',
 'Foreign Language - German',
 'Foreign Language - Greek',
 'Foreign Language - Hindi',
 'Foreign Language - Italian',
 'Foreign Language - Japanese',
 'Foreign Language - Latin',
 'Foreign Language - Persian',
 'Foreign Language - Portuguese',
 'Foreign Language - Russian',
 'Foreign Language - Spanish',
 'Foreign Language-Classical Studies',
 'Foreign Languages',
 'Foreign Languages and Literatures - Arabic',
 'Forestry',
 'Genetic Engineering and Society',
 'Genetics',
 'Geographic Information Systems',
 'Geography',
 'Global Knowledge',
 'Global Public Health',
 'Graduate Economics',
 'Graphic Communications',
 'Graphic Design',
 'Health and Exercise Studies Minor',
 'Health Exercise Studies Dance',
 'Health Exercise Studies Fitness',
 'Health Exercise Studies Outdoor',
 'Health Exercise Studies Racquet',
 'Health Exercise Studies Specialty',
 'Health Exercise Studies Team',
 'HESA - Health Exercise Aquatics',
 'History',
 'History of Art',
 'Honors',
 'Horticulture Science',
 'Humanites and Social Sciences',
 'Humanities',
 'Humanities and Global Knowledge',
 'Humanities and U.S. Diversity',
 'Immunology',
 'Industrial and Systems Engineering',
 'Industrial Design',
 'Integrated Manufacturing Systems',
 'Interdisciplinary Perspectives',
 'Interdisciplinary Perspectives and Global Knowledg',
 'Interdisciplinary Perspectives and U.S. Diversity',
 'Interdisciplinary Studies',
 'International Studies',
 'International Studies',
 'Landscape Architecture',
 'Leadership in the Public Sector',
 'Liberal Studies',
 'Life Sciences First Year',
 'Logic',
 'Management  Innovation  Entrepreneurship',
 'Management',
 'Marine, Earth, and Atmospheric Sciences',
 'Materials Science and Engineering',
 'Math & Science Education',
 'Math in Agriculture and Related Sciences',
 'Mathematical Sciences',
 'Mathematics',
 'Mechanical & Aerospace Engr',
 'Mechanical Engineering Systems',
 'Medical Textiles',
 'Microbiology',
 'Military Science',
 'Multidisciplinary Studies',
 'Music',
 'Natural Resources',
 'Natural Sciences',
 'Natural Sciences and Global Knowledge',
 'Naval Science',
 'NC Global Training Initiative',
 'Nonprofit Studies',
 'Nonwovens',
 'Nuclear Engineering',
 'Nutrition',
 'Occupational Education',
 'Operations Research',
 'Paper Science Engineering',
 'Park Scholars',
 'Parks, Recreation, and Tourism Management',
 'Philosophy',
 'Physics',
 'Physiology',
 'Plant Biology',
 'Plant Pathology',
 'Political Science',
 'Polymer and Color Chemistry',
 'Poultry Science',
 'Professional Writing',
 'Psychology',
 'Public Administration',
 'Religious Studies',
 'Science, Technology and Society',
 'Social Sciences',
 'Social Sciences and Global Knowledge',
 'Social Sciences and U.S. Diversity',
 'Social Work',
 'Sociology',
 'Soil Science',
 'Statistics',
 'Sustanaible Materials and Technology',
 'Technology Education',
 'Technology Engineering and Design Education',
 'Textile and Apparel Management',
 'Textile Chemistry',
 'Textile Engineering',
 'Textile Materials Science',
 'Textile Technology',
 'Textile Technology Management',
 'Textiles',
 'Theatre',
 'Toxicology',
 'U.S. Diversity',
 'University Scholars Program',
 'University Studies Course',
 'Veterinary Medicine-Companion Animal & Sp Species',
 'Veterinary Science - VMB',
 'Veterinary Science - VMP',
 'Visual and Performing Arts',
 'Visual and Performing Arts and Glob Know',
 'Visual and Performing Arts and U.S. Div',
 "Women's, Gender and Sexuality Studies",
 'Wood and Paper Science',
 'Zoology']

In [38]:
x1 = (courses_df_1.CourseDepartment.value_counts(sort=False))
xi2_1 = list(x1)
print(len(xi2_1))
xi2_1

198

[1,
 46,
 84,
 8,
 11,
 34,
 70,
 50,
 11,
 10,
 103,
 68,
 37,
 77,
 70,
 14,
 1,
 49,
 78,
 55,
 42,
 26,
 73,
 7,
 57,
 62,
 48,
 75,
 90,
 180,
 3,
 4,
 108,
 13,
 69,
 1,
 140,
 10,
 59,
 78,
 179,
 8,
 9,
 19,
 6,
 20,
 48,
 34,
 14,
 7,
 177,
 42,
 14,
 228,
 53,
 8,
 6,
 12,
 15,
 23,
 18,
 34,
 12,
 14,
 14,
 49,
 78,
 4,
 13,
 6,
 31,
 22,
 5,
 11,
 8,
 16,
 5,
 6,
 4,
 7,
 52,
 8,
 41,
 12,
 92,
 3,
 59,
 34,
 2,
 1,
 3,
 50,
 10,
 36,
 41,
 13,
 14,
 13,
 5,
 12,
 7,
 9,
 228,
 10,
 35,
 106,
 2,
 1,
 1,
 1,
 6,
 110,
 36,
 5,
 1,
 1,
 1,
 11,
 8,
 7,
 59,
 14,
 5,
 5,
 8,
 25,
 7,
 146,
 86,
 81,
 1,
 1,
 151,
 133,
 11,
 6,
 73,
 10,
 1,
 61,
 35,
 1,
 1,
 10,
 1,
 4,
 9,
 80,
 66,
 5,
 50,
 25,
 4,
 92,
 49,
 82,
 28,
 71,
 48,
 81,
 25,
 59,
 2,
 107,
 68,
 49,
 16,
 1,
 1,
 1,
 60,
 103,
 58,
 127,
 24,
 35,
 22,
 1,
 23,
 38,
 18,
 54,
 41,
 9,
 10,
 33,
 1,
 4,
 25,
 86,
 28,
 52,
 1,
 1,
 1,
 42,
 2,
 19]

In [39]:
lenlist1=[]
for i in range(len(dept1)):
    xi = int(xi2_1[i])
    while(xi!=0):
        lenlist1.append(dept1[i])
        xi = xi-1
        
lenlist1
p1 = pd.DataFrame(lenlist1)

In [40]:
p1

                            0
0     Academy of Data Science
1                  Accounting
2                  Accounting
3                  Accounting
4                  Accounting
...                       ...
7256                  Zoology
7257                  Zoology
7258                  Zoology
7259                  Zoology
7260                  Zoology

[7261 rows x 1 columns]

In [41]:
courses_df_1['Department'] = lenlist1

In [42]:
courses_df_1

,CourseNumber,CourseTitle,Description,CourseDepartment,Department
0,DSC 495,Special Topics in Data Science,Offered as needed to present material not norm...,DSC,Academy of Data Science
1,ACC 200,Introduction to Managerial Accounting,Analysis of accounting data that are useful i...,ACC,Accounting
2,ACC 210,Concepts of Financial Reporting,"Financial reporting concepts, the accounting i...",ACC,Accounting
3,ACC 220,Introduction to Managerial Accounting,The course is designed to provide students wit...,ACC,Accounting
4,ACC 230,Individual Income Taxation,The course focuses on the fundamental concepts...,ACC,Accounting
...,...,...,...,...,...
7256,ZO 553/FW 553,Principles Of Wildlife Science,The principles of wildlife management and thei...,ZO,Zoology
7257,ZO 582/ENT 582,Medical and Veterinary Entomology,"The morphology, taxonomy, biology and control ...",ZO,Zoology
7258,ZO 790,Special Topics,No description for this course,ZO,Zoology
7259,ZO 791,Topics In Animal Behavior,Intensive examination of selected aspects of a...,ZO,Zoology
7260,ZO 829,Special Topics,A directed individual investigation of a parti...,ZO,Zoology

In [43]:
courses_df_1 = courses_df_1.drop(['CourseDepartment'],axis =1)
courses_df_1

,CourseNumber,CourseTitle,Description,Department
0,DSC 495,Special Topics in Data Science,Offered as needed to present material not norm...,Academy of Data Science
1,ACC 200,Introduction to Managerial Accounting,Analysis of accounting data that are useful i...,Accounting
2,ACC 210,Concepts of Financial Reporting,"Financial reporting concepts, the accounting i...",Accounting
3,ACC 220,Introduction to Managerial Accounting,The course is designed to provide students wit...,Accounting
4,ACC 230,Individual Income Taxation,The course focuses on the fundamental concepts...,Accounting
...,...,...,...,...
7256,ZO 553/FW 553,Principles Of Wildlife Science,The principles of wildlife management and thei...,Zoology
7257,ZO 582/ENT 582,Medical and Veterinary Entomology,"The morphology, taxonomy, biology and control ...",Zoology
7258,ZO 790,Special Topics,No description for this course,Zoology
7259,ZO 791,Topics In Animal Behavior,Intensive examination of selected aspects of a...,Zoology
7260,ZO 829,Special Topics,A directed individual investigation of a parti...,Zoology

In [44]:
courses_df_1.rename(columns={'Description':'CourseDescription','Department':'CourseDepartment'}, inplace = True)
courses_df_1

,CourseNumber,CourseTitle,CourseDescription,CourseDepartment
0,DSC 495,Special Topics in Data Science,Offered as needed to present material not norm...,Academy of Data Science
1,ACC 200,Introduction to Managerial Accounting,Analysis of accounting data that are useful i...,Accounting
2,ACC 210,Concepts of Financial Reporting,"Financial reporting concepts, the accounting i...",Accounting
3,ACC 220,Introduction to Managerial Accounting,The course is designed to provide students wit...,Accounting
4,ACC 230,Individual Income Taxation,The course focuses on the fundamental concepts...,Accounting
...,...,...,...,...
7256,ZO 553/FW 553,Principles Of Wildlife Science,The principles of wildlife management and thei...,Zoology
7257,ZO 582/ENT 582,Medical and Veterinary Entomology,"The morphology, taxonomy, biology and control ...",Zoology
7258,ZO 790,Special Topics,No description for this course,Zoology
7259,ZO 791,Topics In Animal Behavior,Intensive examination of selected aspects of a...,Zoology
7260,ZO 829,Special Topics,A directed individual investigation of a parti...,Zoology

In [45]:
courses_df_1.to_csv('../data/courses_temp1.csv', index = None)

In [46]:
courses_df_1.isnull().sum()

CourseNumber         0
CourseTitle          0
CourseDescription    0
CourseDepartment     0
dtype: int64

In [47]:
courses_df_1[courses_df_1['CourseDepartment']=='Accounting']

,CourseNumber,CourseTitle,CourseDescription,CourseDepartment
1,ACC 200,Introduction to Managerial Accounting,Analysis of accounting data that are useful i...,Accounting
2,ACC 210,Concepts of Financial Reporting,"Financial reporting concepts, the accounting i...",Accounting
3,ACC 220,Introduction to Managerial Accounting,The course is designed to provide students wit...,Accounting
4,ACC 230,Individual Income Taxation,The course focuses on the fundamental concepts...,Accounting
5,ACC 280,Survey of Financial and Managerial Accounting,This course covers the basic principles and co...,Accounting
6,ACC 295,Special Topics in Accounting,Presentation of accounting material at the 200...,Accounting
7,ACC 310,Intermediate Financial Accounting I,This course introduces the conceptual framewor...,Accounting
8,ACC 311,Intermediate Financial Accounting II,A continuation of topics introduced in Interme...,Accounting
9,ACC 330,An Introduction To Income Taxation,Basic income tax principles and procedures (in...,Accounting
10,ACC 340,Accounting Information Systems,Accounting is an information system that suppo...,Accounting
11,ACC 411,Business Valuation,"Conceptual framework of how businesses work, v...",Accounting
12,ACC 420,Cost Accounting for Effective Management,Cost Accounting for Effective Management focus...,Accounting
13,ACC 440,Enterprise Resource Planning Systems,Enterprise resource planning (ERP) systems are...,Accounting
14,ACC 450,Auditing and Assurance Services,Introduction to auditing practice and theory. ...,Accounting
15,ACC 451,Internal Auditing,"An overview of the theory, practice, and desi...",Accounting
16,ACC 458/BUS 458,Analytics: From Data to Decisions,Students will develop and apply their data ana...,Accounting
17,ACC 459,Analytics in Accounting and Finance,To enhance the understanding and integration o...,Accounting
18,ACC 460,Governmental and Nonprofit Accounting,Accounting and reporting for state and local g...,Accounting
19,ACC 495,Special Topics in Accounting,Presentation of material not normally availab...,Accounting
20,ACC 498,Independent Study in Accounting,Detailed investigation of topics of particular...,Accounting
21,ACC 499,Internship in ACC,A full-time accounting-related professional in...,Accounting
22,ACC 508,Advanced Commercial Law,A study of law and regulation as a structure i...,Accounting
23,ACC 510,Advanced Financial Accounting,Study of complex financial reporting topics af...,Accounting
24,ACC 519,Applied Financial Management,A study of key business decision made and tool...,Accounting
25,ACC 520,Advanced Management Accounting,A study of how accounting and operating inform...,Accounting
26,ACC 530,Advanced Income Tax,"A study of the tax consequences of business, f...",Accounting
27,ACC 533,Accounting and Tax Research,"A study of research methods, procedures and to...",Accounting
28,ACC 540,IT Risks and Controls,A study of how business strategies use informa...,Accounting
29,ACC 545,Information Technology Audit,Organizational managers and board members reco...,Accounting
30,ACC 550,Advanced Auditing,A study of the impact of business risks on the...,Accounting
31,ACC 560,Tools for Tax Analytics,In this course we will teach the skills needed...,Accounting
32,ACC 561,Database Management in Tax,"In this course, we will teach the skills neede...",Accounting
33,ACC 562,Forecasting Effective Tax Rates and Scenario A...,In this course we will examine the different d...,Accounting
34,ACC 563,Forecasting Effective Tax Rates and Scenario A...,In this course we will continue to examine the...,Accounting
35,ACC 564,Project Management and Process Documentation i...,In this course we will focus on tax project ma...,Accounting
36,ACC 565,Visual Analytics in Tax,We will teach visual analytics to enhance the ...,Accounting
37,ACC 566,Database Management Applications in Tax,"In this course, we will teach the skills neede...",Accounting
38,ACC 567,Enterprise Resource Planning for Tax,"In this course, we will teach Enterprise Resou...",Accounting
39,ACC 568,Analysis of Unstructured Data in Tax,The objective of this course is to get insight...,Accounting
40,ACC 569,Advanced Visual Analytics in Tax,Visualization helps us see and understand the ...,Accounting
41,ACC 570,Data Security and Warehousing in Tax,The course is focused on the importance of dat...,Accounting
42,ACC 571,Enterprise Resource Planning - Advanced Applic...,In this course we will focus on extracting and...,Accounting
43,ACC 580,Data Analytics in Accounting,This course provides an opportunity to learn a...,Accounting
44,ACC 588,Special Topics in Accounting,Course objectives dependent upon unique circum...,Accounting
45,ACC 600,Managerial and Career Effectiveness,Knowledge and skills needed to advance profess...,Accounting
46,ACC 630,Independent Study,Advanced topics not otherwise included in curr...,Accounting